### ISSUE TITLE
API change in FreeBSD 11.1

### ISSUE THREAD

**Issue by disasmwinnie** [truenas/py-libzfs#1]
The compilation on FreeBSD/HardenedBSD 11.1 fails with:

```
libzfs.c:45011:71: error: too few arguments to function call, expected 3, have 2
        __pyx_v_ret = zpool_scan(__pyx_v_self->handle, POOL_SCAN_SCRUB);
```

I remeber compiling py-libzfs on FreeBSD 11.0 successfully, some time ago.
The feature to stop scrubbing, was not only ported to CURRENT, but also went into STABLE (11.1). I don't have the exact kernel version number, since when this happened. My machine is running:

```bash
uname -K
1101505
```

I verified the source of fbsd and hbsd and the zpool_scan() indeed expects three arguments.

The problem can solved by checking ``FREEBSD_VERSION >= 1100000`` instead of ``FREEBSD_VERSION >= 1200044`` in the following: 
https://github.com/freenas/py-libzfs/blob/3e31c3f01ec6648ec0a10ac6bda2955d4a8044d0/libzfs.pyx#L1869
https://github.com/freenas/py-libzfs/blob/3e31c3f01ec6648ec0a10ac6bda2955d4a8044d0/libzfs.pyx#L1883
https://github.com/freenas/py-libzfs/blob/3e31c3f01ec6648ec0a10ac6bda2955d4a8044d0/libzfs.pyx#L1869

However, when I do this I get the following compile error: 

```
Error compiling Cython file:
------------------------------------------------------------
...
    def stop_scrub(self):
        cdef int ret

        with nogil:
            IF EXPERIMENTAL or FREEBSD_VERSION >= 1100044:
                ret = libzfs.zpool_scan(self.handle, zfs.POOL_SCAN_NONE, zfs.POOL_SCRUB_NORMAL)
                                                                           ^
------------------------------------------------------------

libzfs.pyx:1884:76: Converting to Python object not allowed without gil
```

Am stuck at this point.

**Comment by william-gr** [comment]
`Converting to Python object not allowed without gil` error is unknown to me. You may try removing `with nogil` above.

**Comment by disasmwinnie** [comment]
Still fails: 

```

Error compiling Cython file:
------------------------------------------------------------
...
    def start_scrub(self):
        cdef int ret

        #with nogil:
        IF EXPERIMENTAL or FREEBSD_VERSION >= 1100044:
            ret = libzfs.zpool_scan(self.handle, zfs.POOL_SCAN_SCRUB, zfs.POOL_SCRUB_NORMAL)
                                                                        ^
------------------------------------------------------------

libzfs.pyx:1870:73: cimported module has no attribute 'POOL_SCRUB_NORMAL'

```

**Comment by c0decafe** [comment]
try setting the EXPERIMENTAL env to a false value.

`$ EXPERIMENTAL=0 portmaster -Bd devel/py-libzfs`

**Comment by disasmwinnie** [comment]
This workaround worked. Thanks!
I have been certain the zpool_scan method has changed since 11.1, by looking at the source code. I actually expected EXPERIMENTAL as an requirement. @c0decafe do you have an explanation for that?

Either way, this still needs an adjustment for fbsd11.1 to work out of the box.

**Comment by utrenkner** [comment]
Any news on this? FreeBSD ships packages of older version (with some trickery?), HBSD has not been shipping py-libzfs for weeks, as it does not build! Which means: No py-iocage! This is a big problem for me.

**Comment by william-gr** [comment]
As far as I can see 11.1-RELEASE is building just fine, right?

The issue is with 11-STABLE?

**Comment by disasmwinnie** [comment]
No, the issue is with 11.1-STABLE.
There has been a change ZFS/libzfs source in 11.1 and 12. However, 12 is detected correctly. The workaround mentioned by @c0decafe works for 11.1. But building without it, doesn't work out of the box, at least for me. I suspect the function ``libzfs.c:45011:71:`` has changed (see my original post).

**Comment by william-gr** [comment]
Ok, so lets stop referring to 11.1, its a different beast. There is no such thing as 11.1-STABLE, its 11-STABLE

**Comment by william-gr** [comment]
I have a committed a fix to branch `issues/2` and am waiting a 11-stable jail to finish build so I can test it.

If you can give that a try would be appreciated.

**Comment by disasmwinnie** [comment]
Maybe I misspoke, I meant freebsd/hardenedbsd 11.1. I must admit, I am not familiar with FreeNAS release cycles.

> Ok, so lets stop referring to 11.1, its a different beast.

Why?

EDIT: OK thanks, will be able to test in ~4 hours. Will give feedback.

**Comment by william-gr** [comment]
> > Ok, so lets stop referring to 11.1, its a different beast.
> Why?

There is only one stable branch for 11 series, and its called `stable/11` -> 11-STABLE, such there is no 11.1-STABLE.
The branch for 11.1 is `releng/11.1`, which is 11.1-RELEASE-pX

**Comment by william-gr** [comment]
Fixed in https://github.com/freenas/py-libzfs/commit/e0b4b68eeec1383ead97e7219419700c8d24fc39

**Comment by william-gr** [comment]
FreeBSD port updated as well

**Comment by disasmwinnie** [comment]
Can compile on both, fbsd and hbsd. Thank you.

**Comment by utrenkner** [comment]
Many thanks, @william-gr !!! This is great! I just compiled it and with a little bit of fiddling, even the latest iocage runs again on our (HBSD) production server!!!
