### ISSUE TITLE
Need a way to get just one property of a dataset

### ISSUE THREAD

**Issue by asomers** [truenas/py-libzfs#125]
The way to lookup a dataset's properties is to do
```python
dataset.properties['mypropname'].value
```
Unfortunately, the `ZFSObject::properties` property constructs a `ZFSPropertyDict`, which looks up all properties on the dataset, native and user.  Some of these properties can be overridden at mount time, so libzfs calls `getfsstat` to lookup up mountpoint info.  That's roughly equivalent to typing `mount` on the command line.  For servers with many mounted file systems, it can take a long time.  If your application needs to lookup a single property on, say, all snapshots of a dataset, it can take an extremely long time!

It would be very helpful of py-libzfs had a method that could retrieve the value of a single property.  Something like this:
```python
cdef class ZFSObject(object):
   def property(self, propname):
        """ Look up the value of a single property """
        ...
```

**Comment by sonicaj** [comment]
@asomers we have
```
        with libzfs.ZFS() as zfs:
            kwargs = dict(
                props=props, user_props=user_properties, retrieve_children=retrieve_children,
            )
            datasets = zfs.datasets_serialized(**kwargs)
```
You can specify `props` and it will only then retrieve them selectively.

**Comment by sonicaj** [comment]
Btw you can specify `datasets` as well to only limit to certain datasets and not retrieve all of them.

**Comment by asomers** [comment]
Thanks!  That's pretty close to what I need.  However, while `props` is respected for the `datasets`, it seems that this method still fetches all properties for the snapshots, when I specify `snapshots=True`.  Dtrace confirms that `getfsstat` still gets called twice for each snapshot.  Is there a way to prevent that?

**Comment by sonicaj** [comment]
@asomers please refer to `snapshots_serialized` function, it should help you filter properties for snapshots. We don't support specifying properties for snapshots right now when using datasets_serialized endpoint, contributions are always welcome ;)
