### ISSUE TITLE
libzfs.pyx line 2311 "ordinal not in range" error with 12.0-ALPHA2 jails

### ISSUE THREAD

**Issue by agshekeloh** [truenas/py-libzfs#15]
(originally filed with iocage project at https://github.com/iocage/iocage/issues/602, but they say it's really a py-libzfs error, so I'll file it here.)

Iocage is assigned the zpool "iocage."

storm~;iocage --version
Version 1.0 ALPHA 1
storm~;uname -a
FreeBSD storm 12.0-ALPHA3 FreeBSD 12.0-ALPHA3 #9 r338296: Fri Aug 24 15:08:35 EDT 2018     root@storm:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64
storm~;iocage list -r
+---------------+
| Bases fetched |
+===============+
| 11.2-RELEASE  |
+---------------+
| 12.0-ALPHA2   |
+---------------+
storm~;iocage list
+-----+------+-------+--------------+---------------+
| JID | NAME | STATE |   RELEASE    |      IP4      |
+=====+======+=======+==============+===============+
| 4   | wdb1 | up    | 11.2-RELEASE | 203.0.113.236 |
+-----+------+-------+--------------+---------------+
| -   | wdb2 | down  | 12.0-ALPHA2  | 203.0.113.237 |
+-----+------+-------+--------------+---------------+
| 1   | www1 | up    | 11.2-RELEASE | 203.0.113.234 |
+-----+------+-------+--------------+---------------+
| -   | www2 | down  | 12.0-ALPHA2  | 203.0.113.235 |
+-----+------+-------+--------------+---------------+

    Supply the commands used, along with any steps to recreate it.

# iocage start wdb2
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/start.py", line 54, in cli
    ioc.IOCage(jail=jail, rc=rc).start()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1582, in start
    conf = ioc_json.IOCJson(path, silent=self.silent).json_load()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 224, in json_load
    if jail_dataset.mountpoint is None:
  File "libzfs.pyx", line 2311, in libzfs.ZFSDataset.mountpoint.__get__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xee in position 148: ordinal not in range(128)

storm~;iocage get -r boot
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/get.py", line 122, in cli
    jails = ioc.IOCage().get(prop, recursive=True)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1102, in get
    ioc_json.IOCJson(path).json_get_value(prop)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 565, in json_get_value
    conf = self.json_load()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 224, in json_load
    if jail_dataset.mountpoint is None:
  File "libzfs.pyx", line 2311, in libzfs.ZFSDataset.mountpoint.__get__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf4 in position 135: ordinal not in range(128)

# iocage restart www1
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/restart.py", line 41, in cli
    ioc.IOCage(jail=jail).restart(soft)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1268, in restart
    self.stop()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1641, in stop
    conf = ioc_json.IOCJson(path, silent=self.silent, stop=True
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 224, in json_load
    if jail_dataset.mountpoint is None:
  File "libzfs.pyx", line 2311, in libzfs.ZFSDataset.mountpoint.__get__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xee in position 148: ordinal not in range(128)

I destroy the 12.0-ALPHA2 jails, and I can restart www1.

storm~;iocage restart www1
* Stopping www1
  + Running prestop OK
  + Stopping services OK
ioc-www1: removed
  + Removing jail process OK
  + Running poststop OK
* Starting www1
  + Started OK
  + Starting services OK

I still can't do a get:

# storm~;iocage get -r boot
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/get.py", line 122, in cli
    jails = ioc.IOCage().get(prop, recursive=True)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1102, in get
    ioc_json.IOCJson(path).json_get_value(prop)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 565, in json_get_value
    conf = self.json_load()
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 224, in json_load
    if jail_dataset.mountpoint is None:
  File "libzfs.pyx", line 2311, in libzfs.ZFSDataset.mountpoint.__get__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf4 in position 135: ordinal not in range(128)

**Comment by gronke** [comment]
The error occurs in https://github.com/iocage/iocage/blob/c5dd9c6ff02e31a2b22248ffab31353c87f73d08/iocage_lib/ioc_json.py#L224, so you will find that at least one jail dataset is failing to resolve a mountpoint.

@agshekeloh you could isolate this bug from iocage so that it becomes more clear where to find the issue. The pattern for the dataset name is `f"{pool}/iocage/{jail_type}/{jail_uuid}"` while the jail_type is `jails` which means that the following snippet should trigger the issue:

```python3
pool = "zroot" # configure pool
import libzfs
zfs = libzfs.ZFS()

for jail_ds in zfs.get_dataset(f"{pool}/iocage/jails").children:
  print(jail_ds.mountpoint)
```

**Comment by agshekeloh** [comment]
storm~/bin;python3.6 lztest.py
ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ

FWIW, pool and dataset info:

storm~/bin;zpool list
NAME      SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
base      928G  19.6G   908G        -         -     0%     2%  1.00x  ONLINE  -
iocage    928G  2.79G   925G        -         -     0%     0%  1.00x  ONLINE  -
jail      928G  2.92G   925G        -         -     0%     0%  1.00x  ONLINE  -
scratch   928G  3.14M   928G        -         -     0%     0%  1.00x  ONLINE  -
storm~/bin;


storm~/bin;zfs list
NAME                                       USED  AVAIL  REFER  MOUNTPOINT
base                                      19.6G   879G    88K  /base
base/ROOT                                 15.5G   879G    88K  none
base/ROOT/2017-11-17                         8K   879G  1.51G  /
base/ROOT/default                         15.5G   879G  14.1G  /
base/tmp                                   120K   879G   120K  /tmp
base/usr                                  3.35G   879G    88K  /usr
base/usr/home                              569M   879G   569M  /usr/home
base/usr/local                              88K   879G    88K  /usr/local
base/usr/ports                             923M   879G   923M  /usr/ports
base/usr/src                              1.90G   879G  1.90G  /usr/src
base/var                                   712M   879G    88K  /var
base/var/audit                              88K   879G    88K  /var/audit
base/var/crash                             710M   879G   710M  /var/crash
base/var/log                               948K   879G   948K  /var/log
base/var/mail                              112K   879G   112K  /var/mail
base/var/tmp                                88K   879G    88K  /var/tmp
iocage                                    2.79G   896G   100K  /iocage
iocage/iocage                             2.79G   896G   100K  /iocage
iocage/iocage/download                     632M   896G    88K  /iocage/download
iocage/iocage/download/11.2-RELEASE        272M   896G   272M  /iocage/download/11.2-RELEASE
iocage/iocage/download/12.0-ALPHA2         360M   896G   360M  /iocage/download/12.0-ALPHA2
iocage/iocage/images                        88K   896G    88K  /iocage/images
iocage/iocage/jails                       25.4M   896G    88K  /iocage/jails
iocage/iocage/jails/wdb1                  10.7M   896G    92K  /iocage/jails/wdb1
iocage/iocage/jails/wdb1/root             10.6M   896G   972M  /iocage/jails/wdb1/root
iocage/iocage/jails/wdb2                   292K   896G    92K  /iocage/jails/wdb2
iocage/iocage/jails/wdb2/root              200K   896G  1.19G  /iocage/jails/wdb2/root
iocage/iocage/jails/www1                  14.0M   896G    92K  /iocage/jails/www1
iocage/iocage/jails/www1/root             13.9M   896G   973M  /iocage/jails/www1/root
iocage/iocage/jails/www2                   292K   896G    92K  /iocage/jails/www2
iocage/iocage/jails/www2/root              200K   896G  1.19G  /iocage/jails/www2/root
iocage/iocage/log                           96K   896G    96K  /iocage/log
iocage/iocage/releases                    2.15G   896G    88K  /iocage/releases
iocage/iocage/releases/11.2-RELEASE        983M   896G    88K  /iocage/releases/11.2-RELEASE
iocage/iocage/releases/11.2-RELEASE/root   983M   896G   972M  /iocage/releases/11.2-RELEASE/root
iocage/iocage/releases/12.0-ALPHA2        1.19G   896G    88K  /iocage/releases/12.0-ALPHA2
iocage/iocage/releases/12.0-ALPHA2/root   1.19G   896G  1.19G  /iocage/releases/12.0-ALPHA2/root
iocage/iocage/templates                     88K   896G    88K  /iocage/templates
jail                                      2.92G   896G  2.91G  /jail
scratch                                   2.90M   899G    88K  /scratch
storm~/bin;

**Comment by gronke** [comment]
Thanks for confirming it.

**Comment by agshekeloh** [comment]
This bug is holding up writing my book on jails, so: I'm available for testing every day.

**Comment by gronke** [comment]
Have you tried with the latest version of py-libzfs?

```
pkg remove -y py36-libzfs
pkg install -y py36-setuptools
git clone https://github.com/freenas/py-libzfs
cd py-libzfs/
PYTHON=`which python3.6` make install
```

What's the output of [the snippet](https://github.com/freenas/py-libzfs/issues/15#issuecomment-415979627) after compiling from master?

**Comment by agshekeloh** [comment]
storm~/bin;python3.6 lztest.py
/iocage/jails/www2
/iocage/jails/wdb2
/iocage/jails/www1
/iocage/jails/wdb1

Makes more sense. So, the iocage people need to pull in your master. Is there going to be a new py-libzfs release any time soon?

**Comment by gronke** [comment]
The installation from git source only worked because your `/usr/src` was checked out:

```
base/usr/src 1.90G 879G 1.90G /usr/src
```

So recommending the installation from source is not suitable for all iocage users. iocage can and should not automate this for the same reason.

Due to the usage of cython this package cannot be installed with regular pip, but needs to (pre-)compiled with sources available. The most user friendly way of installing it via pre-built pkg fails due to the [general lack of interest in maintaining releases not targeted by FreeNAS](https://github.com/freenas/iocage-ix-plugins/issues/35#issuecomment-407135166). Enough people showing their interest in frequent releases supporting pkg in CURRENT can hopefully lead to a shift in that position.

I volunteer to establish monitoring for the built packages on all non-EOL releases for HardenedBSD and FreeBSD with warnings via GitHub Issue if somebody promises to read them. 🔧😄

**Comment by jhixson74** [comment]
On Sat, Aug 25, 2018 at 03:36:30PM -0700, Stefan Grönke wrote:
>    The installation from git source only worked because your /usr/src was
>    checked out:
> 
>  base/usr/src 1.90G 879G 1.90G /usr/src
> 
>    So recommending the installation from source is not suitable for all
>    iocage users. iocage can and should not automate this for the same reason.
> 
>    Due to the usage of cython this package cannot be installed with regular
>    pip, but needs to (pre-)compiled with sources available. The most user
>    friendly way of installing it via pre-built pkg fails due to the general
>    lack of interest in maintaining releases not targeted by FreeNAS. Enough
>    people showing their interest in frequent releases supporting pkg in
>    CURRENT can hopefully lead to a shift in that position.
> 
>    I volunteer to establish monitoring for the built packages on all non-EOL
>    releases for HardenedBSD and FreeBSD with warnings via GitHub Issue if
>    somebody promises to read them. ð**§ð***
> 
>    —
>    You are receiving this because you are subscribed to this thread.
>    Reply to this email directly, view it on GitHub, or mute the thread.


I'm late to the game here, but this is fixed in TrueOS:

--- libzfs.pyx.orig     2017-05-28 14:29:59 UTC
+++ libzfs.pyx
@@ -2258,7 +2258,8 @@ cdef class ZFSDataset(ZFSObject):
             if libzfs.zfs_is_mounted(self.handle, &mntpt) == 0:
                 return None

-            result = mntpt
+            encoded = mntpt.encode('utf-8')
+            result = encoded
             free(mntpt)
             return result

- John
