### ISSUE TITLE
Comparison to pyzfs

### ISSUE THREAD

**Issue by deliciouslytyped** [truenas/py-libzfs#62]
How does this project relate to https://github.com/zfsonlinux/zfs/tree/master/contrib/pyzfs ?

**Comment by sonicaj** [comment]
Iirc that only exposes llbzfs_core which is not sufficient wrt the api py-libzfs currently exposes. @william-gr can perhaps confirm this ?

**Comment by deliciouslytyped** [comment]
https://pyzfs.readthedocs.io/en/latest/ does indeed seem to cover less.

**Comment by william-gr** [comment]
pyzfs uses libzfs_core which in turn is an attempt of a thread-safe library but it lacks dozens of features still.

libzfs provides all the funcionality but it is not thread-safe and the API is not public, so to speak.
