### ISSUE TITLE
API Coverage Requests

### ISSUE THREAD

**Issue by deliciouslytyped** [truenas/py-libzfs#63]
I'm trying to port https://github.com/volkerp/zfstui to py-libzfs, which uses some rather simple interactions with the CLI tools to show it's data. Are you open to expanding the coverage of the library?

I haven't gotten too far into it yet but what I'm immediately missing is
- [ ] `zpool history`
- [ ] ability to read out short column names (low priority)
https://github.com/zfsonlinux/zfs/blob/c81f1790e28a547769ce9d8e2d25391cf4317cc0/cmd/zpool/zpool_main.c#L5438 -> https://github.com/zfsonlinux/zfs/blob/c81f1790e28a547769ce9d8e2d25391cf4317cc0/module/zcommon/zpool_prop.c#L246

**Comment by william-gr** [comment]
We have our own use case for the API, we will happily accept PRs for any missing feature but unfortunately we dont have the cycles to write new things by community request.
