### ISSUE TITLE
configure fails on debian buster

### ISSUE THREAD

**Issue by luqasz** [truenas/py-libzfs#76]
On debian 10 (buster) 
```
CFLAGS="-I/usr/include/libspl -I/usr/include/libzfs/ -I/usr/src/zfs-0.8.2/include/ -D_LARGEFILE64_SOURCE" ./configure
``` 
fails with [config.log](https://pastebin.com/74C4Hvmt)

 with plain `./configure` [config.log](https://pastebin.com/Xyib6wT3)

**Comment by sonicaj** [comment]
@luqasz when running `./configure` you need to specify `prefix` like the following,
`./configure prefix=/usr`
Usually this is `/usr` for debian ( assuming you have installed the `libzfslinux-dev` package ).
It will tell the configure script to look for header files under `/usr`,
Existence of `/usr/include/libzfs/libzfs.h` is tested, if not found it defaults to FreeBSD paths for sources.

Please confirm if this resolves the issue for you. Thank you

**Comment by luqasz** [comment]
Hi.
Works but I had to change prefix when installing and building in Makefile. I've created a debian directory with all required files to build a deb package. Would you like me to create a PR for it ?

**Comment by sonicaj** [comment]
Can you please check freenas/12-devel brach ?
We have a debian directory already, please have a peek. It should fit your needs. Also that branch would become master soon in case you’re curious.
