### ISSUE TITLE
Github CI

### ISSUE THREAD

**Issue by luqasz** [truenas/py-libzfs#79]
Hi. 

I was thinking about adding github actions CI to this repo. It could produce a valid `deb` package as a artifact. Also do some basic testing and validation.

What do you think ?

**Comment by william-gr** [comment]
Yes, I think that would be great, do you think you can help us set that up?

**Comment by luqasz** [comment]
Yes. I will make a PR for that.

**Comment by luqasz** [comment]
see #80
